---
# tasks file for ansible-role-vaultwarden

- name: Ensure vaultwarden logrotate configuration up-to-date
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/vaultwarden
    owner: 0
    group: 0
    mode: "0644"
  notify:
    - reload fail2ban
