---
# tasks file for ansible-role-vaultwarden

- name: Ensure vaultwarden image is pulled
  docker_image:
    name: "{{ vaultwarden_docker_image }}"
    tag: "{{ vaultwarden_docker_image_tag }}"
    source: pull

- name: Ensure data container is created
  docker_container:
    name: "{{ vaultwarden_container_name }}-data"
    image: "{{ vaultwarden_docker_image }}:{{ vaultwarden_docker_image_tag }}"
    container_default_behavior: no_defaults
    pull: "{{ vaultwarden_upgrade | default(false) | bool }}"
    state: present
  notify:
    - restart vaultwarden

- name: Ensure vaultwarden container runs
  docker_container:
    name: "{{ vaultwarden_container_name }}"
    image: "{{ vaultwarden_docker_image }}:{{ vaultwarden_docker_image_tag }}"
    restart_policy: always
    state: started
    restart: yes
    memory: "{{ vaultwarden_container_memory_limit | default(omit) }}"
    volumes:
      - "{{ vaultwarden_container_name }}-data:/data"
    volumes_from:
      - "{{ vaultwarden_container_name }}-data"
    ports:
      # - "{{ vaultwarden_port }}:80"
      - "{{ vaultwarden_internal_port }}"
    env: "{{ vaultwarden_config }}"
    container_default_behavior: no_defaults
    networks: "{{ vaultwarden_networks }}"
    networks_cli_compatible: yes
    network_mode: default
  notify:
    - restart vaultwarden
