---
# handlers file for ansible-role-vaultwarden

- name: Ensure vaultwarden container runs
  docker_container:
    name: "{{ vaultwarden_container_name }}"
    restart_policy: always
    state: started
    restart: yes
  listen: start vaultwarden

# - name: Ensure vaultwarden container runs
#   docker_container:
#     name: "{{ vaultwarden_container_name }}"
#     image: "{{ vaultwarden_docker_image }}:{{ vaultwarden_docker_image_tag }}"
#     restart_policy: always
#     state: started
#     restart: yes
#     memory: "{{ vaultwarden_container_memory_limit | default(omit) }}"
#     volumes:
#       - "{{ vaultwarden_container_name }}-data:/data"
#       - "{{ vaultwarden_logfile_mount_str | default(omit) }}"
#     # volumes_from:
#     #   - "{{ vaultwarden_container_name }}-data"
#     ports: "{{ vaultwarden_internal_ports }}"
#     env: "{{ vaultwarden_compiled_config }}"
#     container_default_behavior: no_defaults
#     networks: "{{ vaultwarden_networks }}"
#     networks_cli_compatible: yes
#     network_mode: default
#   listen: start vaultwarden

- name: Wait until Vaultwarden starts up
  wait_for:
    port: "{{ vaultwarden_internal_ports[0] }}" # TODO: Maybe check all?
    delay: 5
  listen: start vaultwarden

- name: Reload fail2ban
  systemd:
    name: fail2ban
    state: reloaded
  listen: reload fail2ban
