---
# handlers file for ansible-role-odoo

- name: Restart Vaultwarden
  command: "docker restart {{ vaultwarden_container_name }}"
  listen: restart vaultwarden

- name: Wait until Vaultwarden starts up
  wait_for:
    port: "{{ vaultwarden_internal_ports[0] }}" # TODO: Maybe check all?
    delay: 5
  listen: restart vaultwarden

- name: Reload fail2ban
  systemd:
    name: fail2ban
    state: reloaded
  listen: reload fail2ban
